var price = 399;
// console.log(typeof price);
var isHappy = true;
// console.log(isHappy);
var romantic;
// console.log(typeof romantic);
var num1 = 0.1;
var num2 = 0.2;
var sum = num1 + num2;
sum = sum.toFixed(3);
sum = parseFloat(sum);
console.log(sum);